export const MOCK_DATA = {
    "residential": [
        {
            "category": "residential",
            "City": "Chennai",
            "State": "Tamil Nadu",
            "Pincode": 600001,
            "Installations": 125,
            "Capacity_kW": 520,
            "Savings_Estimate": 1250000,
            "District": "Chennai District",
            "Date": "1/10/2026",
            "Legacy_3Yr_Active": 45,
            "Legacy_3Yr_Total": 85,
            "Legacy_5Yr_Active": 28,
            "Legacy_5Yr_Total": 45,
            "Legacy_10Yr_Active": 10,
            "Legacy_10Yr_Total": 15,
            "Service_Avg_Downtime": 2.5,
            "Service_3Yr_Downtime": 2,
            "Service_5Yr_Downtime": 2.5,
            "Service_10Yr_Downtime": 3.3,
            "Service_3Yr_VisitTime": 1.5,
            "Service_5Yr_VisitTime": 2.2,
            "Service_10Yr_VisitTime": 2,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "residential",
            "City": "Coimbatore",
            "State": "Tamil Nadu",
            "Pincode": 641001,
            "Installations": 85,
            "Capacity_kW": 360,
            "Savings_Estimate": 820000,
            "Date": "1/12/2026",
            "Legacy_3Yr_Active": 30,
            "Legacy_3Yr_Total": 50,
            "Legacy_5Yr_Active": 20,
            "Legacy_5Yr_Total": 35,
            "Legacy_10Yr_Active": 8,
            "Legacy_10Yr_Total": 12,
            "Service_Avg_Downtime": 3.1,
            "Service_3Yr_Downtime": 2.5,
            "Service_5Yr_Downtime": 3.1,
            "Service_10Yr_Downtime": 4,
            "Service_3Yr_VisitTime": 1.9,
            "Service_5Yr_VisitTime": 2.4,
            "Service_10Yr_VisitTime": 3,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "residential",
            "City": "Bengaluru",
            "State": "Karnataka",
            "Pincode": 560001,
            "Installations": 210,
            "Capacity_kW": 890,
            "Savings_Estimate": 2100000,
            "Date": "1/15/2026",
            "Legacy_3Yr_Active": 85,
            "Legacy_3Yr_Total": 120,
            "Legacy_5Yr_Active": 50,
            "Legacy_5Yr_Total": 80,
            "Legacy_10Yr_Active": 20,
            "Legacy_10Yr_Total": 35,
            "Service_Avg_Downtime": 2.8,
            "Service_3Yr_Downtime": 2.2,
            "Service_5Yr_Downtime": 2.8,
            "Service_10Yr_Downtime": 3.6,
            "Service_3Yr_VisitTime": 1.5,
            "Service_5Yr_VisitTime": 1.5,
            "Service_10Yr_VisitTime": 2.6,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "residential",
            "City": "Pune",
            "State": "Maharashtra",
            "Pincode": 411001,
            "Installations": 140,
            "Capacity_kW": 590,
            "Savings_Estimate": 1350000,
            "Date": "1/22/2026",
            "Legacy_3Yr_Active": 55,
            "Legacy_3Yr_Total": 90,
            "Legacy_5Yr_Active": 35,
            "Legacy_5Yr_Total": 65,
            "Legacy_10Yr_Active": 14,
            "Legacy_10Yr_Total": 20,
            "Service_Avg_Downtime": 3.4,
            "Service_3Yr_Downtime": 2.7,
            "Service_5Yr_Downtime": 3.4,
            "Service_10Yr_Downtime": 4.4,
            "Service_3Yr_VisitTime": 1.8,
            "Service_5Yr_VisitTime": 1.8,
            "Service_10Yr_VisitTime": 2.2,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "residential",
            "City": "Salem",
            "State": "Tamil Nadu",
            "Pincode": 636001,
            "Installations": 65,
            "Capacity_kW": 280,
            "Savings_Estimate": 650000,
            "Date": "1/30/2026",
            "Legacy_3Yr_Active": 19,
            "Legacy_3Yr_Total": 45,
            "Legacy_5Yr_Active": 14,
            "Legacy_5Yr_Total": 25,
            "Legacy_10Yr_Active": 5,
            "Legacy_10Yr_Total": 8,
            "Service_Avg_Downtime": 3,
            "Service_3Yr_Downtime": 2.4,
            "Service_5Yr_Downtime": 3,
            "Service_10Yr_Downtime": 3.9,
            "Service_3Yr_VisitTime": 1.6,
            "Service_5Yr_VisitTime": 1.7,
            "Service_10Yr_VisitTime": 2.7,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        }
    ],
    "commercial": [
        {
            "category": "commercial",
            "City": "Hyderabad",
            "State": "Telangana",
            "Pincode": 500001,
            "Installations": 150,
            "Capacity_kW": 6400,
            "Savings_Estimate": 14800000,
            "Date": "1/18/2026",
            "Legacy_3Yr_Active": 110,
            "Legacy_3Yr_Total": 140,
            "Legacy_5Yr_Active": 85,
            "Legacy_5Yr_Total": 115,
            "Legacy_10Yr_Active": 45,
            "Legacy_10Yr_Total": 60,
            "Service_Avg_Downtime": 4.5,
            "Service_3Yr_Downtime": 3.6,
            "Service_5Yr_Downtime": 4.5,
            "Service_10Yr_Downtime": 5.9,
            "Service_3Yr_VisitTime": 1.9,
            "Service_5Yr_VisitTime": 1.6,
            "Service_10Yr_VisitTime": 2.5,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "commercial",
            "City": "Mumbai",
            "State": "Maharashtra",
            "Pincode": 400001,
            "Installations": 260,
            "Capacity_kW": 11000,
            "Savings_Estimate": 27500000,
            "Date": "1/20/2026",
            "Legacy_3Yr_Active": 190,
            "Legacy_3Yr_Total": 240,
            "Legacy_5Yr_Active": 140,
            "Legacy_5Yr_Total": 190,
            "Legacy_10Yr_Active": 80,
            "Legacy_10Yr_Total": 110,
            "Service_Avg_Downtime": 5.1,
            "Service_3Yr_Downtime": 4.1,
            "Service_5Yr_Downtime": 5.1,
            "Service_10Yr_Downtime": 6.6,
            "Service_3Yr_VisitTime": 1.5,
            "Service_5Yr_VisitTime": 1.6,
            "Service_10Yr_VisitTime": 2.8,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "commercial",
            "City": "Delhi",
            "State": "Delhi",
            "Pincode": 110001,
            "Installations": 300,
            "Capacity_kW": 13000,
            "Savings_Estimate": 32000000,
            "Date": "1/25/2026",
            "Legacy_3Yr_Active": 210,
            "Legacy_3Yr_Total": 280,
            "Legacy_5Yr_Active": 160,
            "Legacy_5Yr_Total": 220,
            "Legacy_10Yr_Active": 95,
            "Legacy_10Yr_Total": 130,
            "Service_Avg_Downtime": 4.8,
            "Service_3Yr_Downtime": 3.8,
            "Service_5Yr_Downtime": 4.8,
            "Service_10Yr_Downtime": 6.2,
            "Service_3Yr_VisitTime": 1.9,
            "Service_5Yr_VisitTime": 1.7,
            "Service_10Yr_VisitTime": 2.4,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "commercial",
            "City": "Kolkata",
            "State": "West Bengal",
            "Pincode": 700001,
            "Installations": 120,
            "Capacity_kW": 5000,
            "Savings_Estimate": 11500000,
            "Date": "1/27/2026",
            "Legacy_3Yr_Active": 85,
            "Legacy_3Yr_Total": 110,
            "Legacy_5Yr_Active": 60,
            "Legacy_5Yr_Total": 90,
            "Legacy_10Yr_Active": 35,
            "Legacy_10Yr_Total": 50,
            "Service_Avg_Downtime": 4.2,
            "Service_3Yr_Downtime": 3.4,
            "Service_5Yr_Downtime": 4.2,
            "Service_10Yr_Downtime": 5.5,
            "Service_3Yr_VisitTime": 1.7,
            "Service_5Yr_VisitTime": 1.7,
            "Service_10Yr_VisitTime": 2.5,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        }
    ],
    "waterHeater": [
        {
            "category": "waterHeater",
            "City": "Tiruppur",
            "State": "Tamil Nadu",
            "Pincode": 641601,
            "Installations": 95,
            "Capacity_kW": 41,
            "Savings_Estimate": 95000,
            "Date": "1/28/2026",
            "Legacy_3Yr_Active": 25,
            "Legacy_3Yr_Total": 35,
            "Legacy_5Yr_Active": 15,
            "Legacy_5Yr_Total": 20,
            "Legacy_10Yr_Active": 5,
            "Legacy_10Yr_Total": 10,
            "Service_Avg_Downtime": 1.2,
            "Service_3Yr_Downtime": 1,
            "Service_5Yr_Downtime": 1.2,
            "Service_10Yr_Downtime": 1.6,
            "Service_3Yr_VisitTime": 1.5,
            "Service_5Yr_VisitTime": 2,
            "Service_10Yr_VisitTime": 2.3,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "waterHeater",
            "City": "Erode",
            "State": "Tamil Nadu",
            "Pincode": 638001,
            "Installations": 70,
            "Capacity_kW": 30,
            "Savings_Estimate": 70000,
            "Date": "1/29/2026",
            "Legacy_3Yr_Active": 18,
            "Legacy_3Yr_Total": 25,
            "Legacy_5Yr_Active": 12,
            "Legacy_5Yr_Total": 18,
            "Legacy_10Yr_Active": 4,
            "Legacy_10Yr_Total": 8,
            "Service_Avg_Downtime": 1.5,
            "Service_3Yr_Downtime": 1.2,
            "Service_5Yr_Downtime": 1.5,
            "Service_10Yr_Downtime": 2,
            "Service_3Yr_VisitTime": 1.4,
            "Service_5Yr_VisitTime": 2.2,
            "Service_10Yr_VisitTime": 2.8,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "waterHeater",
            "City": "Madurai",
            "State": "Tamil Nadu",
            "Pincode": 625001,
            "Installations": 110,
            "Capacity_kW": 48,
            "Savings_Estimate": 110000,
            "Date": "2/01/2026",
            "Legacy_3Yr_Active": 30,
            "Legacy_3Yr_Total": 45,
            "Legacy_5Yr_Active": 20,
            "Legacy_5Yr_Total": 30,
            "Legacy_10Yr_Active": 8,
            "Legacy_10Yr_Total": 14,
            "Service_Avg_Downtime": 1.8,
            "Service_3Yr_Downtime": 1.4,
            "Service_5Yr_Downtime": 1.8,
            "Service_10Yr_Downtime": 2.3,
            "Service_3Yr_VisitTime": 1,
            "Service_5Yr_VisitTime": 2.2,
            "Service_10Yr_VisitTime": 2.8,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        },
        {
            "category": "waterHeater",
            "City": "Trichy",
            "State": "Tamil Nadu",
            "Pincode": 620001,
            "Installations": 90,
            "Capacity_kW": 39,
            "Savings_Estimate": 90000,
            "Date": "2/02/2026",
            "Legacy_3Yr_Active": 22,
            "Legacy_3Yr_Total": 32,
            "Legacy_5Yr_Active": 14,
            "Legacy_5Yr_Total": 22,
            "Legacy_10Yr_Active": 6,
            "Legacy_10Yr_Total": 10,
            "Service_Avg_Downtime": 1.4,
            "Service_3Yr_Downtime": 1.1,
            "Service_5Yr_Downtime": 1.4,
            "Service_10Yr_Downtime": 1.8,
            "Service_3Yr_VisitTime": 1.6,
            "Service_5Yr_VisitTime": 2.2,
            "Service_10Yr_VisitTime": 2.5,
            "Service_3Yr_Visits": 4,
            "Service_5Yr_Visits": 4,
            "Service_10Yr_Visits": 4
        }
    ]
};

export const fetchMockData = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve({ status: 'success', data: MOCK_DATA });
        }, 0);
    });
};
